import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{ChevronLeft,ChevronRight,Copy,Plus,Trash2,Users,Utensils,X}from'lucide-react';import'./style.css';
const days=['Måndag','Tisdag','Onsdag','Torsdag','Fredag','Lördag','Söndag'],colors=['#16a34a','#2563eb','#db2777','#ea580c','#7c3aed','#0891b2'];
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},mon=d=>{const x=new Date(d),n=x.getDay()||7;x.setHours(12,0,0,0);x.setDate(x.getDate()-n+1);return x},week=d=>{const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));return Math.ceil((((x-new Date(Date.UTC(x.getUTCFullYear(),0,1)))/86400000)+1)/7)};
const api=async(p,o={})=>{const r=await fetch('/api'+p,{credentials:'include',headers:{'content-type':'application/json'},...o});if(r.status===401)throw Error('AUTH');if(!r.ok)throw Error(await r.text());return r.json()};
function App(){const [auth,setAuth]=useState(null),[pin,setPin]=useState(''),[sync,setSync]=useState('Ansluter...'),[members,setMembers]=useState([]),[acts,setActs]=useState([]),[meals,setMeals]=useState(days.map(day=>({day,dish:'',url:''}))),[ws,setWs]=useState(mon(new Date())),[modal,setModal]=useState(null),[memberModal,setMemberModal]=useState(false),[newName,setNewName]=useState('');const wd=useMemo(()=>days.map((_,i)=>add(ws,i)),[ws]);
useEffect(()=>{api('/state').then(r=>{if(r.data){setMembers(r.data.members||[]);setActs(r.data.activities||[]);setMeals(r.data.meals||meals)}setAuth(true);setSync('Synkroniserad')}).catch(e=>setAuth(e.message==='AUTH'?false:null))},[]);
useEffect(()=>{if(!auth)return;setSync('Sparar...');const t=setTimeout(()=>api('/state',{method:'PUT',body:JSON.stringify({members,activities:acts,meals})}).then(()=>setSync('Synkroniserad')).catch(()=>setSync('Synkfel')),500);return()=>clearTimeout(t)},[auth,members,acts,meals]);
const login=e=>{e.preventDefault();api('/login',{method:'POST',body:JSON.stringify({pin})}).then(()=>location.reload()).catch(()=>setSync('Fel familjekod'))};
if(auth===null)return <div className="splash">Laddar familjeportalen...</div>;if(!auth)return <div className="login"><form onSubmit={login}><small>PRIVAT FAMILJEPORTAL</small><h1>Familjeplaneraren</h1><p>Ange familjekoden för att synkronisera mellan enheter.</p><input type="password" value={pin} onChange={e=>setPin(e.target.value)} autoFocus placeholder="Familjekod"/><button>Logga in</button><em>{sync}</em></form></div>;
const end=a=>a.endDate||a.date,occurs=(a,d)=>a.date<=d&&end(a)>=d,weekActs=acts.filter(a=>a.date<=iso(wd[6])&&end(a)>=iso(wd[0]));const empty=d=>({id:null,title:'',members:members[0]?[members[0].id]:[],date:d,endDate:d,start:'17:00',end:'18:00',place:''});const edit=a=>setModal({...a,endDate:end(a),members:[...a.members]});const save=()=>{if(!modal.title.trim()||!modal.members.length||modal.endDate<modal.date)return;setActs(v=>modal.id?v.map(a=>a.id===modal.id?modal:a):[...v,{...modal,id:Date.now()}]);setModal(null)};const copy=()=>{setActs(v=>[...v,{...modal,id:Date.now(),title:modal.title+' (kopia)',members:[...modal.members]}]);setModal(null)};
return <div><header><div><small>FAMILJENS GEMENSAMMA YTA</small><h1>Familjeportalen</h1><p>{sync}</p></div><div className="nav"><button onClick={()=>setMemberModal(true)}><Users/> Familjemedlemmar</button><button onClick={()=>setModal(empty(iso(wd[0])))}><Plus/> Aktivitet</button></div></header><main><div className="weeknav"><button onClick={()=>setWs(add(ws,-7))}><ChevronLeft/></button><b>Vecka {week(ws)}</b><span>{iso(wd[0])} till {iso(wd[6])}</span><button onClick={()=>setWs(add(ws,7))}><ChevronRight/></button></div><div className="layout"><section className="calendar"><div className="grid head"><b>Familjemedlem</b>{wd.map((d,i)=><div><small>{days[i]}</small><strong>{d.getDate()}</strong></div>)}</div>{members.map(m=><div className="grid row" key={m.id}><div className="who"><i style={{background:m.color}}/>{m.name}</div>{wd.map(d=><button className="cell" onDoubleClick={()=>setModal(empty(iso(d)))}>{acts.filter(a=>a.members.includes(m.id)&&occurs(a,iso(d))).map(a=><span style={{background:m.color}} onClick={e=>{e.stopPropagation();edit(a)}}>{a.title}<small>{a.start}–{a.end}</small></span>)}</button>)}</div>)}</section><aside><h2><Utensils/> Veckans mat</h2>{meals.map((m,i)=><button className="meal" onClick={()=>{const dish=prompt(`${m.day}: maträtt`,m.dish);if(dish!==null){const url=prompt('Receptlänk (valfritt)',m.url)||'';setMeals(v=>v.map((x,j)=>j===i?{...x,dish,url}:x))}}}><b>{m.day}</b><span>{m.dish||'Ingen maträtt'}</span>{m.url&&<a href={m.url} target="_blank" onClick={e=>e.stopPropagation()}>Recept</a>}</button>)}</aside></div><h2>Planerade aktiviteter</h2>{weekActs.map(a=><button className="summary" onClick={()=>edit(a)}><b>{a.title}</b><span>{a.date}{end(a)!==a.date?` till ${end(a)}`:''} · {a.start}–{a.end}</span></button>)}</main>
{modal&&<div className="shade" onMouseDown={()=>setModal(null)}><div className="dialog" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button><h2>{modal.id?'Redigera aktivitet':'Ny aktivitet'}</h2><input value={modal.title} onChange={e=>setModal({...modal,title:e.target.value})} placeholder="Aktivitet"/><div className="checks">{members.map(m=><label><input type="checkbox" checked={modal.members.includes(m.id)} onChange={()=>setModal(x=>({...x,members:x.members.includes(m.id)?x.members.filter(i=>i!==m.id):[...x.members,m.id]}))}/>{m.name}</label>)}</div><div className="cols"><label>Från<input type="date" value={modal.date} onChange={e=>setModal({...modal,date:e.target.value,endDate:modal.endDate<e.target.value?e.target.value:modal.endDate})}/></label><label>Till<input type="date" min={modal.date} value={modal.endDate} onChange={e=>setModal({...modal,endDate:e.target.value})}/></label></div><div className="cols"><label>Start<input type="time" value={modal.start} onChange={e=>setModal({...modal,start:e.target.value})}/></label><label>Slut<input type="time" value={modal.end} onChange={e=>setModal({...modal,end:e.target.value})}/></label></div><input value={modal.place} onChange={e=>setModal({...modal,place:e.target.value})} placeholder="Plats"/><div className="actions">{modal.id&&<button className="danger" onClick={()=>{setActs(v=>v.filter(a=>a.id!==modal.id));setModal(null)}}><Trash2/></button>}{modal.id&&<button onClick={copy}><Copy/> Kopiera</button>}<button className="primary" onClick={save}>Spara</button></div></div></div>}
{memberModal&&<div className="shade" onMouseDown={()=>setMemberModal(false)}><div className="dialog" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setMemberModal(false)}><X/></button><h2>Familjemedlemmar</h2><div className="cols"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Namn"/><button onClick={()=>{if(newName.trim()){setMembers(v=>[...v,{id:'m-'+Date.now(),name:newName.trim(),color:colors[v.length%colors.length]}]);setNewName('')}}}><Plus/></button></div>{members.map(m=><div className="member"><i style={{background:m.color}}/><b>{m.name}</b><button onClick={()=>setMembers(v=>v.filter(x=>x.id!==m.id))}><Trash2/></button></div>)}</div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
