import React, { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, ExternalLink, Pencil, Plus, Trash2, Users, Utensils, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
const STORAGE_KEY="familjeplaneraren-v2";
const initialMembers=[{id:"andreas",name:"Andreas",color:"#16a34a"},{id:"vuxen2",name:"Vuxen 2",color:"#2563eb"},{id:"wilma",name:"Wilma",color:"#db2777"},{id:"olle",name:"Olle",color:"#ea580c"}];
const colors=["#16a34a","#2563eb","#db2777","#ea580c","#7c3aed","#0891b2","#dc2626","#ca8a04"];
const days=["Måndag","Tisdag","Onsdag","Torsdag","Fredag","Lördag","Söndag"];
const dishes=["Köttfärssås och spaghetti","Kycklinggryta med ris","Fisk med potatis","Pannkakor","Tacos","Hemgjord pizza","Rester / valfritt"];
const pad=n=>String(n).padStart(2,"0"),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const mondayOf=date=>{const d=new Date(date),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1);return d};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},fmt=d=>d.toLocaleDateString("sv-SE",{day:"numeric",month:"short"});
const weekNo=date=>{const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)};
const todayLong=d=>{const s=d.toLocaleDateString("sv-SE",{weekday:"long",day:"numeric",month:"long"});return s[0].toUpperCase()+s.slice(1)};
const namedays={"08-25":"Lovisa och Louise","08-26":"Östen","08-27":"Raoul och Rolf","08-28":"Fatima och Leila","08-29":"Hampus och Hans","08-30":"Albert och Albertina","08-31":"Arvid och Vidar","09-01":"Sam och Samuel"};
const initialMeals=days.map((day,i)=>({day,dish:dishes[i],url:""}));
const initialActivities=()=>[{id:1,title:"Fotbollsträning",members:["olle"],date:iso(addDays(mondayOf(new Date()),1)),start:"17:30",end:"19:00",place:"Stöde IP"},{id:2,title:"Tandläkare",members:["wilma","andreas"],date:iso(addDays(mondayOf(new Date()),3)),start:"09:00",end:"10:00",place:"Sundsvall"}];
export default function App(){
 const [loaded,setLoaded]=useState(false),[members,setMembers]=useState(initialMembers),[activities,setActivities]=useState(initialActivities),[meals,setMeals]=useState(initialMeals),[weekStart,setWeekStart]=useState(mondayOf(new Date())),[tab,setTab]=useState("plan");
 const weekDays=useMemo(()=>Array.from({length:7},(_,i)=>addDays(weekStart,i)),[weekStart]);
 const empty=()=>({id:null,title:"",members:members[0]?[members[0].id]:[],date:iso(weekDays[0]),start:"17:00",end:"18:00",place:""});
 const [draft,setDraft]=useState(empty),[modal,setModal]=useState(false),[memberModal,setMemberModal]=useState(false),[newName,setNewName]=useState(""),[mealModal,setMealModal]=useState(false),[mealIndex,setMealIndex]=useState(0),[mealDraft,setMealDraft]=useState({dish:"",url:""});
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const d=JSON.parse(raw);if(Array.isArray(d.members))setMembers(d.members);if(Array.isArray(d.activities))setActivities(d.activities);if(Array.isArray(d.meals))setMeals(d.meals)}}catch(e){console.warn(e)}finally{setLoaded(true)}},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEY,JSON.stringify({members,activities,meals}))},[loaded,members,activities,meals]);
 const weekActs=activities.filter(a=>weekDays.some(d=>iso(d)===a.date)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)),findMember=id=>members.find(m=>m.id===id);
 const openNew=(date=iso(weekDays[0]))=>{setDraft({...empty(),date});setModal(true)},openEdit=a=>{setDraft({...a,members:[...a.members]});setModal(true)};
 const save=()=>{if(!draft.title.trim()||!draft.members.length)return;setActivities(v=>draft.id?v.map(a=>a.id===draft.id?draft:a):[...v,{...draft,id:Date.now()}]);setModal(false)};
 const addMember=()=>{const name=newName.trim();if(!name)return;setMembers(v=>[...v,{id:`m-${Date.now()}`,name,color:colors[v.length%colors.length]}]);setNewName("")};
 const removeMember=id=>{setMembers(v=>v.filter(m=>m.id!==id));setActivities(v=>v.map(a=>({...a,members:a.members.filter(x=>x!==id)})).filter(a=>a.members.length))};
 const openMeal=i=>{setMealIndex(i);setMealDraft({dish:meals[i].dish,url:meals[i].url});setMealModal(true)},saveMeal=()=>{setMeals(v=>v.map((m,i)=>i===mealIndex?{...m,...mealDraft}:m));setMealModal(false)};
 const today=new Date(),key=`${pad(today.getMonth()+1)}-${pad(today.getDate())}`,dateLabel=`${fmt(weekDays[0])} – ${fmt(weekDays[6])} ${weekDays[6].getFullYear()}`;
 const MealList=()=> <section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-4 h-fit"><div className="flex items-center gap-2 mb-3"><Utensils className="text-emerald-700" size={19}/><div><h2 className="font-black">Veckans mat</h2><p className="text-[11px] text-slate-500">Välj en dag för att redigera</p></div></div><div className="divide-y divide-slate-100">{meals.map((m,i)=><div key={m.day} className="flex items-center gap-2 py-1.5"><button onClick={()=>openMeal(i)} className="min-w-0 flex-1 grid grid-cols-[70px_1fr] gap-2 items-center text-left rounded-lg hover:bg-slate-50 p-1.5"><b className="text-xs text-emerald-800">{m.day}</b><span className={`text-sm truncate ${m.dish?"":"text-slate-400 italic"}`}>{m.dish||"Ingen maträtt"}</span></button>{m.url&&<a href={m.url} target="_blank" rel="noreferrer" className="p-2 rounded-lg bg-emerald-50 text-emerald-700"><ExternalLink size={15}/></a>}</div>)}</div></section>;
 return <div className="min-h-screen bg-[#f6f7f4] text-slate-800"><header className="bg-[#173e31] text-white"><div className="mx-auto max-w-[1700px] px-4 py-5 md:px-8 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="text-sm font-semibold text-emerald-300 uppercase tracking-[.18em]">Familjens gemensamma yta</div><h1 className="text-3xl font-bold mt-1">Familjeplaneraren</h1><div className="mt-2 text-sm flex gap-3"><span>{todayLong(today)}</span><span className="text-emerald-300">Namnsdag: <b>{namedays[key]||"Ingen uppgift"}</b></span></div></div><nav className="bg-white/10 p-1 rounded-2xl flex">{[["plan","Planering",CalendarDays],["summary","Sammanställning",Users]].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold ${tab===id?"bg-white text-[#173e31]":""}`}><Icon size={17}/>{label}</button>)}</nav></div></header>
 <main className="mx-auto max-w-[1700px] p-4 md:p-8"><div className="grid grid-cols-3 gap-3 mb-5 max-w-2xl">{[[weekActs.length,"aktiviteter"],[members.length,"familjemedlemmar"],[meals.filter(m=>m.dish.trim()).length,"middagar"]].map(([n,l])=><div key={l} className="bg-white border rounded-2xl p-3"><div className="text-2xl font-black">{n}</div><div className="text-xs text-slate-500">{l}</div></div>)}</div>
 <div className="flex flex-wrap gap-3 items-center justify-between mb-6"><div className="flex items-center bg-white rounded-2xl p-1.5 border"><button className="p-2" onClick={()=>setWeekStart(addDays(weekStart,-7))}><ChevronLeft/></button><button className="px-3 min-w-52" onClick={()=>setWeekStart(mondayOf(new Date()))}><b className="block text-sm">Vecka {weekNo(weekStart)}</b><span className="text-xs text-slate-500">{dateLabel}</span></button><button className="p-2" onClick={()=>setWeekStart(addDays(weekStart,7))}><ChevronRight/></button></div>{tab==="plan"&&<div className="flex gap-2"><button onClick={()=>setMemberModal(true)} className="flex items-center gap-2 bg-white border font-bold px-4 py-3 rounded-2xl"><Users size={18}/> Familjemedlemmar</button><button onClick={()=>openNew()} className="flex items-center gap-2 bg-emerald-600 text-white font-bold px-4 py-3 rounded-2xl"><Plus size={19}/> Aktivitet</button></div>}</div>
 {tab==="plan"&&<div className="grid xl:grid-cols-[minmax(0,1fr)_330px] gap-6"><section className="bg-white rounded-3xl border overflow-hidden"><div className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-[140px_repeat(7,minmax(105px,1fr))] border-b"><div className="p-4 text-xs font-bold">Familjemedlem</div>{weekDays.map((d,i)=><div key={iso(d)} className={`p-3 border-l text-center ${iso(d)===iso(today)?"bg-emerald-50":""}`}><div className="text-xs font-bold text-slate-500">{days[i]}</div><b>{d.getDate()}</b></div>)}</div>{members.map(m=><div key={m.id} className="grid grid-cols-[140px_repeat(7,minmax(105px,1fr))] min-h-28 border-b"><div className="p-4 bg-slate-50 flex gap-2"><span className="w-3 h-3 rounded-full mt-1" style={{background:m.color}}/><b>{m.name}</b></div>{weekDays.map(d=><button key={iso(d)} onDoubleClick={()=>openNew(iso(d))} className="border-l p-2 text-left"><div className="space-y-2">{activities.filter(a=>a.members.includes(m.id)&&a.date===iso(d)).map(a=><div key={a.id} onClick={e=>{e.stopPropagation();openEdit(a)}} className="rounded-xl p-2.5 text-white cursor-pointer" style={{background:m.color}}><b className="text-sm">{a.title}</b><div className="text-xs">{a.start}–{a.end}</div><div className="text-[10px] mt-2 flex gap-1"><Pencil size={11}/> Redigera</div></div>)}</div></button>)}</div>)}</div></div></section><MealList/></div>}
 {tab==="summary"&&<div className="grid xl:grid-cols-[minmax(0,1fr)_330px] gap-6"><section className="bg-white rounded-3xl border p-5"><h2 className="text-xl font-black mb-4">Planerade aktiviteter</h2><div className="space-y-3">{weekActs.map(a=><button onClick={()=>openEdit(a)} key={a.id} className="w-full text-left p-4 rounded-2xl border bg-slate-50"><b>{a.title}</b><div className="text-sm text-slate-500">{days[weekDays.findIndex(d=>iso(d)===a.date)]} {a.start}–{a.end}{a.place?` · ${a.place}`:""}</div><div className="flex gap-2 mt-2">{a.members.map(findMember).filter(Boolean).map(m=><span key={m.id} className="text-xs text-white rounded-full px-2 py-1" style={{background:m.color}}>{m.name}</span>)}</div></button>)}</div></section><MealList/></div>}</main>
 <AnimatePresence>{modal&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onMouseDown={()=>setModal(false)}><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl bg-white rounded-3xl p-6"><div className="flex justify-between"><h2 className="text-xl font-black">{draft.id?"Redigera aktivitet":"Ny aktivitet"}</h2><button onClick={()=>setModal(false)}><X/></button></div><div className="space-y-4 mt-5"><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="w-full border rounded-xl p-3" placeholder="Aktivitet"/><div className="grid sm:grid-cols-2 gap-2">{members.map(m=><label key={m.id} className="flex gap-3 border rounded-xl p-3"><input type="checkbox" checked={draft.members.includes(m.id)} onChange={()=>setDraft(d=>({...d,members:d.members.includes(m.id)?d.members.filter(x=>x!==m.id):[...d.members,m.id]}))}/><b>{m.name}</b></label>)}</div><div className="grid grid-cols-3 gap-3"><input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})} className="border rounded-xl p-3"/><input type="time" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})} className="border rounded-xl p-3"/><input type="time" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})} className="border rounded-xl p-3"/></div><input value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})} className="w-full border rounded-xl p-3" placeholder="Plats"/></div><div className="flex gap-3 mt-6">{draft.id&&<button onClick={()=>{setActivities(v=>v.filter(a=>a.id!==draft.id));setModal(false)}} className="p-3 border text-red-700 rounded-2xl"><Trash2/></button>}<button onClick={save} className="flex-1 bg-emerald-600 text-white font-black rounded-2xl">Spara</button></div></motion.div></div>}
 {mealModal&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onMouseDown={()=>setMealModal(false)}><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-md bg-white rounded-3xl p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Redigera {meals[mealIndex]?.day}</h2><button onClick={()=>setMealModal(false)}><X/></button></div><input value={mealDraft.dish} onChange={e=>setMealDraft({...mealDraft,dish:e.target.value})} className="w-full border rounded-xl p-3 mt-5" placeholder="Maträtt"/><input value={mealDraft.url} onChange={e=>setMealDraft({...mealDraft,url:e.target.value})} className="w-full border rounded-xl p-3 mt-3" placeholder="Receptlänk"/><button onClick={saveMeal} className="mt-6 w-full bg-emerald-600 text-white font-black py-3 rounded-2xl">Spara</button></motion.div></div>}
 {memberModal&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onMouseDown={()=>setMemberModal(false)}><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-md bg-white rounded-3xl p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Familjemedlemmar</h2><button onClick={()=>setMemberModal(false)}><X/></button></div><div className="flex gap-2 my-4"><input value={newName} onChange={e=>setNewName(e.target.value)} className="flex-1 border rounded-xl p-3" placeholder="Namn"/><button onClick={addMember} className="bg-emerald-600 text-white rounded-xl px-4"><Plus/></button></div>{members.map(m=><div key={m.id} className="flex items-center gap-3 border rounded-xl p-3 mb-2"><span className="w-4 h-4 rounded-full" style={{background:m.color}}/><b className="flex-1">{m.name}</b><button onClick={()=>removeMember(m.id)} className="text-red-600"><Trash2 size={18}/></button></div>)}</motion.div></div>}</AnimatePresence></div>
}
