import React,{useEffect,useMemo,useState}from"react";import{ChevronLeft,ChevronRight,Copy,ExternalLink,Plus,Trash2,Users,X}from"lucide-react";
const KEY="familjeplaneraren-v3",days=["Måndag","Tisdag","Onsdag","Torsdag","Fredag","Lördag","Söndag"],colors=["#16a34a","#2563eb","#db2777","#ea580c","#7c3aed","#0891b2"];
const pad=n=>String(n).padStart(2,"0"),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x},monday=d=>{let x=new Date(d),n=x.getDay()||7;x.setHours(12,0,0,0);x.setDate(x.getDate()-n+1);return x};
const initMembers=[{id:"a",name:"Andreas",color:colors[0]},{id:"w",name:"Wilma",color:colors[2]},{id:"o",name:"Olle",color:colors[3]}],initMeals=days.map(day=>({day,dish:"",url:""}));
export default function App(){const[week,setWeek]=useState(monday(new Date())),[members,setMembers]=useState(initMembers),[acts,setActs]=useState([]),[meals,setMeals]=useState(initMeals),[modal,setModal]=useState(false),[memberModal,setMemberModal]=useState(false),[mealEdit,setMealEdit]=useState(null),[newName,setNewName]=useState("");const weekDays=useMemo(()=>days.map((_,i)=>add(week,i)),[week]);
const empty=(date=iso(weekDays[0]))=>({id:null,title:"",members:members[0]?[members[0].id]:[],date,endDate:date,start:"17:00",end:"18:00",place:""});const[draft,setDraft]=useState(empty());
useEffect(()=>{try{let d=JSON.parse(localStorage.getItem(KEY)||"null");if(d){setMembers(d.members||initMembers);setActs((d.acts||[]).map(a=>({...a,endDate:a.endDate||a.date})));setMeals(d.meals||initMeals)}}catch{}},[]);useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({members,acts,meals}))},[members,acts,meals]);
const occurs=(a,date)=>a.date<=date&&(a.endDate||a.date)>=date,openNew=date=>{setDraft(empty(date));setModal(true)},openEdit=a=>{setDraft({...a,endDate:a.endDate||a.date,members:[...a.members]});setModal(true)},toggle=id=>setDraft(d=>({...d,members:d.members.includes(id)?d.members.filter(x=>x!==id):[...d.members,id]}));
const save=()=>{if(!draft.title.trim()||!draft.members.length||draft.endDate<draft.date)return;setActs(v=>draft.id?v.map(a=>a.id===draft.id?draft:a):[...v,{...draft,id:Date.now()}]);setModal(false)},copy=()=>{let c={...draft,id:Date.now(),title:`Kopia av ${draft.title}`,members:[...draft.members]};setActs(v=>[...v,c]);setModal(false)},del=()=>{setActs(v=>v.filter(a=>a.id!==draft.id));setModal(false)};
const addMember=()=>{if(!newName.trim())return;setMembers(v=>[...v,{id:`m${Date.now()}`,name:newName.trim(),color:colors[v.length%colors.length]}]);setNewName("")},removeMember=id=>{setMembers(v=>v.filter(m=>m.id!==id));setActs(v=>v.map(a=>({...a,members:a.members.filter(x=>x!==id)})).filter(a=>a.members.length))};
return <><header className="header"><b>FAMILJENS GEMENSAMMA YTA</b><h1>Familjeplaneraren</h1></header><main className="wrap"><div className="toolbar"><div className="row"><button className="btn" onClick={()=>setWeek(add(week,-7))}><ChevronLeft/></button><button className="btn" onClick={()=>setWeek(monday(new Date()))}>{iso(weekDays[0])} till {iso(weekDays[6])}</button><button className="btn" onClick={()=>setWeek(add(week,7))}><ChevronRight/></button></div><div className="row"><button className="btn" onClick={()=>setMemberModal(true)}><Users size={17}/> Familjemedlemmar</button><button className="btn primary" onClick={()=>openNew(iso(weekDays[0]))}><Plus size={17}/> Aktivitet</button></div></div><div className="layout"><section className="card timeline"><div className="grid"><div className="gridrow head"><div className="name">Familjemedlem</div>{weekDays.map((d,i)=><div className="cell" key={i}><b>{days[i]}</b><br/>{d.getDate()}</div>)}</div>{members.map(m=><div className="gridrow" key={m.id}><div className="name"><i className="dot" style={{background:m.color}}/>{m.name}</div>{weekDays.map(d=><div className="cell" key={iso(d)} onDoubleClick={()=>openNew(iso(d))}>{acts.filter(a=>a.members.includes(m.id)&&occurs(a,iso(d))).map(a=><div className="activity" style={{background:m.color}} key={a.id} onClick={()=>openEdit(a)} title={`${a.title}
${a.date}${a.endDate!==a.date?` till ${a.endDate}`:""}
${a.start}-${a.end}${a.place?`
${a.place}`:""}`}><b>{a.title}</b><small>{a.start}-{a.end}</small></div>)}</div>)}</div>)}</div></section><aside className="card meals"><h3>Veckans mat</h3>{meals.map((m,i)=><div className="meal" key={m.day}><b>{m.day}</b><button onClick={()=>setMealEdit(i)}>{m.dish||"Ingen maträtt"}</button>{m.url&&<a href={m.url} target="_blank"><ExternalLink size={16}/></a>}</div>)}</aside></div></main>
{modal&&<div className="modalback" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="btn" style={{float:"right"}} onClick={()=>setModal(false)}><X/></button><h2>{draft.id?"Redigera aktivitet":"Ny aktivitet"}</h2><label className="field">Aktivitet<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><b>Familjemedlemmar</b><div className="members">{members.map(m=><label className={`check ${draft.members.includes(m.id)?"selected":""}`} key={m.id}><input type="checkbox" checked={draft.members.includes(m.id)} onChange={()=>toggle(m.id)}/> {m.name}</label>)}</div><div className="two"><label className="field">Från datum<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value,endDate:draft.endDate<e.target.value?e.target.value:draft.endDate})}/></label><label className="field">Till datum<input type="date" min={draft.date} value={draft.endDate} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></label></div><div className="two"><label className="field">Starttid<input type="time" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label className="field">Sluttid<input type="time" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label></div><label className="field">Plats<input value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})}/></label><div className="modal-actions">{draft.id&&<><button className="btn blue" onClick={copy}><Copy size={17}/> Kopiera</button><button className="btn danger" onClick={del}><Trash2/></button></>}<button className="btn primary" onClick={save}>Spara</button></div></div></div>}
{mealEdit!==null&&<div className="modalback" onMouseDown={()=>setMealEdit(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><h2>Redigera {meals[mealEdit].day}</h2><label className="field">Maträtt<input value={meals[mealEdit].dish} onChange={e=>setMeals(v=>v.map((m,i)=>i===mealEdit?{...m,dish:e.target.value}:m))}/></label><label className="field">Receptlänk<input value={meals[mealEdit].url} onChange={e=>setMeals(v=>v.map((m,i)=>i===mealEdit?{...m,url:e.target.value}:m))}/></label><button className="btn primary" onClick={()=>setMealEdit(null)}>Spara</button></div></div>}
{memberModal&&<div className="modalback" onMouseDown={()=>setMemberModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><h2>Familjemedlemmar</h2><div className="row"><input className="field" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Namn"/><button className="btn primary" onClick={addMember}><Plus/></button></div>{members.map(m=><div className="meal" key={m.id}><i className="dot" style={{background:m.color}}/><b>{m.name}</b><button className="btn danger" onClick={()=>removeMember(m.id)}><Trash2 size={16}/></button></div>)}<button className="btn" onClick={()=>setMemberModal(false)}>Stäng</button></div></div>}</>}
